name: scm-uq-workflow
channels:
  - conda-forge
dependencies:
  - python>=3.10
  - ipykernel
  - ipywidgets
  - jupyter
  - matplotlib
  - nco
  - netcdf4
  - notebook
  - numpy
  - pandas
  - plotly
  - pyyaml
  - reportlab
  - scipy
  - scikit-learn
  - xarray
  - pip
  - pip:
      - qmcpy
