name: scm-uq-workflow
channels:
  - conda-forge
dependencies:
  - python>=3.10
  - matplotlib
  - netcdf4
  - numpy
  - pandas
  - pyyaml
  - scipy
  - scikit-learn
  - xarray
  - pip
  - pip:
      - qmcpy
